### ISSUE TITLE
Navigation to left, mid, or right view controllers?

### ISSUE THREAD

**Issue by HackShitUp** [jakespracher/Snapchat-Swipe-View#12]
Is there a way to navigate to between view controllers? Pushing it won't work because it'll be pushed over the current context, I just want it to sort of, "swipe" to the specified view controller?

**Comment by HackShitUp** [comment]
bump

**Comment by jackcolley** [comment]
I wanted to know this as well before using it in a project I'm starting. After looking at the code, it looks to just be using a regular scrollview. So you could use any of the methods you'd normally use to scroll a scrollview programatically. Hope that made sense. 

@jakespracher would you be open to a PR that adds a method to scroll to a certain page?

**Comment by jakespracher** [comment]
Sure thing

**Comment by xtremeactor** [comment]
Hi,
I'm trying to figure out how to programmatically scroll/navigate to a specific view controller and can't figure it out. Would you be so kind to advise how to access the scroll view and set the content offset accordingly? I tried to do it by accessing SnapContainer but the compiler is finding nil.  Can't seem to figure out how to trigger a button to scroll to either the left or right VCs. 

Thanks!!

**Comment by ssgutierrez42** [comment]
@HackShitUp 
Try this: https://github.com/ssgutierrez42/Snapchat-Swipe-View

**Comment by HackShitUp** [comment]
@ssgutierrez42 Thanks but I decided to forgo using this framework for a few reasons.
