### ISSUE TITLE
Stop Scroll

### ISSUE THREAD

**Issue by vishaldeshai** [jakespracher/Snapchat-Swipe-View#5]
IS it possible to stop scrolling when Top view Controller appears(i am talking about left and right scrolling).

Is it possible to make transparent top view Controller..

Thanks in advance.

**Comment by jakespracher** [comment]
Yeah whoops I thought this was the default behavior, guess I never added it. I'll add an option to do this

**Comment by vishaldeshai** [comment]
I did it through protocols.

**Comment by jakespracher** [comment]
This is now the default behavior 0f802bce314a9f4984080cdf928eaabfd5767f1e

**Comment by vishaldeshai** [comment]
Ok fine.

is it possible like top view move on above middle view and topview as a transparent sam like Snapchat?

**Comment by jakespracher** [comment]
https://github.com/jakespracher/Snapchat-Swipe-View/issues/3
